   
<!-- Slider
======================================= -->  

<div class="container_full">

	
	<div class="slider_mer_minus">
    
    <div class="fullwidthbanner-container">
		<div class="fullwidthbanner">
        
						<ul>
							<!-- SLIDE 1 -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/spacer.gif">

								<img src="/themes/hostingycloud/images/spacer.gif" alt="" />
                                
                                <div class="caption lfr" data-x="450" data-y="0" data-speed="900" data-start="400" data-easing="easeOutBack"><img src="/themes/hostingycloud/images/sliders/revolution/1.png" alt="" /></div>
								<div class="caption lft big_white"  data-x="0" data-y="55" data-speed="400" data-start="1000" data-easing="easeOutExpo">Reliable host</div>
								<div class="caption lft big_orange"  data-x="4" data-y="125" data-speed="400" data-start="1300" data-easing="easeOutExpo">Reliability service for your website</div>
								<div class="caption lfl medium_grey"  data-x="4" data-y="172" data-speed="400" data-start="1800" data-easing="easeOutExpo">Internet tend to repeat predefined chunks as necessary<br />
making this the first true generator on the internet.</div>
                                <div class="caption sfb" data-x="4" data-y="242" data-speed="300" data-start="2100" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="240" data-speed="300" data-start="2100" data-easing="easeOutExpo">Unlimited Bandwidth with Massive Storage</div>
                                <div class="caption sfb" data-x="4" data-y="272" data-speed="300" data-start="2200" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="270" data-speed="300" data-start="2200" data-easing="easeOutExpo">Unlimited Databases and Email Addresses</div>
                                <div class="caption sfb" data-x="4" data-y="302" data-speed="300" data-start="2300" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="300" data-speed="300" data-start="2300" data-easing="easeOutExpo">99.99% Uptime Guarantee &amp; 24/7 Live Support</div>
                                <div class="caption sfb" data-x="4" data-y="332" data-speed="300" data-start="2400" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="330" data-speed="300" data-start="2400" data-easing="easeOutExpo">Apps Including WordPress, Drupal and Joomla</div>
                                <div class="caption sfb" data-x="4" data-y="362" data-speed="300" data-start="2500" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="360" data-speed="300" data-start="2500" data-easing="easeOutExpo">Easy to use Website Builder &amp; one-click Setup</div>
                                <div class="caption sfb" data-x="0" data-y="406" data-speed="300" data-start="3000" data-easing="easeOutExpo"><a href="#" class="slider_button1">view details&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="171" data-y="406" data-speed="300" data-start="3400" data-easing="easeOutExpo"><a href="#" class="slider_button2">sign up now&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="790" data-y="230" data-speed="300" data-start="3800" data-easing="easeOutExpo">
                                	<div class="round1">get free<br /><i>Domain</i> with<br />Annual<br />Plan</div>
                                </div>
                                <div class="caption sfb" data-x="845" data-y="295" data-speed="300" data-start="4000" data-easing="easeOutExpo">
                                	<div class="price">from only<br /><i>$4.99</i><br />/m</div>
                                </div>
							</li>
                            
                            
                            <!-- SLIDE 2 -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/spacer.gif">

								<img src="/themes/hostingycloud/images/spacer.gif" alt="" />
                                
                                <div class="caption lfr" data-x="450" data-y="0" data-speed="900" data-start="400" data-easing="easeOutBack"><img src="/themes/hostingycloud/images/sliders/revolution/2.png" alt="" /></div>
								<div class="caption lft big_white"  data-x="0" data-y="55" data-speed="400" data-start="1000" data-easing="easeOutExpo">Advanced Host</div>
								<div class="caption lft big_orange"  data-x="4" data-y="125" data-speed="400" data-start="1300" data-easing="easeOutExpo">Simply dummy text for printing type</div>
								<div class="caption lfl medium_grey"  data-x="4" data-y="172" data-speed="400" data-start="1800" data-easing="easeOutExpo">Internet tend to repeat predefined chunks as necessary<br />
making this the first true generator on the internet.</div>
                                <div class="caption sfb" data-x="4" data-y="242" data-speed="300" data-start="2100" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="240" data-speed="300" data-start="2100" data-easing="easeOutExpo">Unlimited Bandwidth with Massive Storage</div>
                                <div class="caption sfb" data-x="4" data-y="272" data-speed="300" data-start="2200" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="270" data-speed="300" data-start="2200" data-easing="easeOutExpo">Unlimited Databases and Email Addresses</div>
                                <div class="caption sfb" data-x="4" data-y="302" data-speed="300" data-start="2300" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="300" data-speed="300" data-start="2300" data-easing="easeOutExpo">99.99% Uptime Guarantee &amp; 24/7 Live Support</div>
                                <div class="caption sfb" data-x="4" data-y="332" data-speed="300" data-start="2400" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="330" data-speed="300" data-start="2400" data-easing="easeOutExpo">Apps Including WordPress, Drupal and Joomla</div>
                                <div class="caption sfb" data-x="4" data-y="362" data-speed="300" data-start="2500" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="360" data-speed="300" data-start="2500" data-easing="easeOutExpo">Easy to use Website Builder &amp; one-click Setup</div>
                                <div class="caption sfb" data-x="0" data-y="406" data-speed="300" data-start="3000" data-easing="easeOutExpo"><a href="#" class="slider_button1">view details&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="171" data-y="406" data-speed="300" data-start="3400" data-easing="easeOutExpo"><a href="#" class="slider_button2">sign up now&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="570" data-y="270" data-speed="300" data-start="3800" data-easing="easeOutExpo">
                                	<div class="round1">get free<br /><i>Domain</i> with<br />Annual<br />Plan</div>
                                </div>
                                <div class="caption sfb" data-x="625" data-y="335" data-speed="300" data-start="4000" data-easing="easeOutExpo">
                                	<div class="price">from only<br /><i>$36</i><br />/m</div>
                                </div>
							</li>
                            
                            
                            
                            <!-- SLIDE 3 -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/spacer.gif">

								<img src="/themes/hostingycloud/images/spacer.gif" alt="" />
                                
                                <div class="caption lft" data-x="450" data-y="0" data-speed="900" data-start="400" data-easing="easeOutBack"><img src="/themes/hostingycloud/images/sliders/revolution/3.png" alt="" /></div>
								<div class="caption lft big_white"  data-x="0" data-y="55" data-speed="400" data-start="1000" data-easing="easeOutExpo">dedicated servers</div>
								<div class="caption lft big_orange"  data-x="4" data-y="125" data-speed="400" data-start="1300" data-easing="easeOutExpo">Simply dummy text for printing type</div>
								<div class="caption lfl medium_grey"  data-x="4" data-y="172" data-speed="400" data-start="1800" data-easing="easeOutExpo">Internet tend to repeat predefined chunks as necessary<br />
making this the first true generator on the internet.</div>
                                <div class="caption sfb" data-x="4" data-y="242" data-speed="300" data-start="2100" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="240" data-speed="300" data-start="2100" data-easing="easeOutExpo">Unlimited Bandwidth with Massive Storage</div>
                                <div class="caption sfb" data-x="4" data-y="272" data-speed="300" data-start="2200" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="270" data-speed="300" data-start="2200" data-easing="easeOutExpo">Unlimited Databases and Email Addresses</div>
                                <div class="caption sfb" data-x="4" data-y="302" data-speed="300" data-start="2300" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="300" data-speed="300" data-start="2300" data-easing="easeOutExpo">99.99% Uptime Guarantee &amp; 24/7 Live Support</div>
                                <div class="caption sfb" data-x="4" data-y="332" data-speed="300" data-start="2400" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="330" data-speed="300" data-start="2400" data-easing="easeOutExpo">Apps Including WordPress, Drupal and Joomla</div>
                                <div class="caption sfb" data-x="4" data-y="362" data-speed="300" data-start="2500" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="360" data-speed="300" data-start="2500" data-easing="easeOutExpo">Easy to use Website Builder &amp; one-click Setup</div>
                                <div class="caption sfb" data-x="0" data-y="406" data-speed="300" data-start="3000" data-easing="easeOutExpo"><a href="#" class="slider_button1">view details&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="171" data-y="406" data-speed="300" data-start="3400" data-easing="easeOutExpo"><a href="#" class="slider_button2">sign up now&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="760" data-y="260" data-speed="300" data-start="3800" data-easing="easeOutExpo">
                                	<div class="round1">get free<br /><i>Domain</i> with<br />Annual<br />Plan</div>
                                </div>
                                <div class="caption sfb" data-x="815" data-y="325" data-speed="300" data-start="4000" data-easing="easeOutExpo">
                                	<div class="price">from only<br /><i>$180</i><br />/m</div>
                                </div>
							</li>
                            
                            
                            <!-- SLIDE 4 -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/spacer.gif">

								<img src="/themes/hostingycloud/images/spacer.gif" alt="" />
                                
                                <div class="caption lfb" data-x="450" data-y="0" data-speed="900" data-start="400" data-easing="easeOutBack"><img src="/themes/hostingycloud/images/sliders/revolution/4.png" alt="" /></div>
								<div class="caption lft big_white"  data-x="0" data-y="55" data-speed="400" data-start="1000" data-easing="easeOutExpo">cloud computing</div>
								<div class="caption lft big_orange"  data-x="4" data-y="125" data-speed="400" data-start="1300" data-easing="easeOutExpo">Simply dummy text for printing type</div>
								<div class="caption lfl medium_grey"  data-x="4" data-y="172" data-speed="400" data-start="1800" data-easing="easeOutExpo">Internet tend to repeat predefined chunks as necessary<br />
making this the first true generator on the internet.</div>
                                <div class="caption sfb" data-x="4" data-y="242" data-speed="300" data-start="2100" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="240" data-speed="300" data-start="2100" data-easing="easeOutExpo">Unlimited Bandwidth with Massive Storage</div>
                                <div class="caption sfb" data-x="4" data-y="272" data-speed="300" data-start="2200" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="270" data-speed="300" data-start="2200" data-easing="easeOutExpo">Unlimited Databases and Email Addresses</div>
                                <div class="caption sfb" data-x="4" data-y="302" data-speed="300" data-start="2300" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="300" data-speed="300" data-start="2300" data-easing="easeOutExpo">99.99% Uptime Guarantee &amp; 24/7 Live Support</div>
                                <div class="caption sfb" data-x="4" data-y="332" data-speed="300" data-start="2400" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="330" data-speed="300" data-start="2400" data-easing="easeOutExpo">Apps Including WordPress, Drupal and Joomla</div>
                                <div class="caption sfb" data-x="4" data-y="362" data-speed="300" data-start="2500" data-easing="easeOutExpo"><img src="/themes/hostingycloud/images/sliders/revolution/check.png" alt="" class="sright_icon" /></div>
                                <div class="caption lfb small_text"  data-x="34" data-y="360" data-speed="300" data-start="2500" data-easing="easeOutExpo">Easy to use Website Builder &amp; one-click Setup</div>
                                <div class="caption sfb" data-x="0" data-y="406" data-speed="300" data-start="3000" data-easing="easeOutExpo"><a href="#" class="slider_button1">view details&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="171" data-y="406" data-speed="300" data-start="3400" data-easing="easeOutExpo"><a href="#" class="slider_button2">sign up now&nbsp;&nbsp;&nbsp;</a></div>
                                <div class="caption sfb" data-x="410" data-y="270" data-speed="300" data-start="3800" data-easing="easeOutExpo">
                                	<div class="round1">get free<br /><i>Domain</i> with<br />Annual<br />Plan</div>
                                </div>
                                <div class="caption sfb" data-x="465" data-y="335" data-speed="300" data-start="4000" data-easing="easeOutExpo">
                                	<div class="price">from only<br /><i>$270</i><br />/m</div>
                                </div>
							</li>
                            
							
						</ul>
                        
					</div>
                    
				</div>
                
                </div>

</div><!-- end slider -->
 
<div class="clearfix mar_top3"></div>

<div class="container">

	<div class="features_section">

    	<h2>Make your Web site Visible to the World <i>Fast and flexible website creator is the easy way to build and manage a site for your business</i></h2>
    	
        <div class="sections">
        	<div class="left"><img src="/themes/hostingycloud/images/site-icon11.png" alt="" /></div>
			<div class="right">
            <h4>Host Your webSite</h4>
            <p>Makings of this the first true generator on the Internet.</p>
            </div>
		</div><!-- end section -->
        
        <div class="sections last">
        	<div class="left"><img src="/themes/hostingycloud/images/site-icon12.png" alt="" /></div>
			<div class="right">
            <h4>Domain Names</h4>
            <p>Makings of this the first true generator on the Internet.</p>
            </div>
		</div><!-- end section -->
        
        <div class="clearfix mar_top2"></div>
        
        <div class="sections">
        	<div class="left"><img src="/themes/hostingycloud/images/site-icon13.png" alt="" /></div>
			<div class="right">
            <h4>CLOUD SERVERs</h4>
            <p>Makings of this the first true generator on the Internet.</p>
            </div>
		</div><!-- end section -->
        
        <div class="sections last">
        	<div class="left"><img src="/themes/hostingycloud/images/site-icon14.png" alt="" /></div>
			<div class="right">
            <h4>HOSTing SOLUTIONS</h4>
            <p>Makings of this the first true generator on the Internet.</p>
            </div>
		</div><!-- end section -->
        
    </div><!-- end all sections -->
    
    
    <div class="whats_new">
    
    	<h2>What’s new at aoxhost <i>Web hosting services offers and new features</i></h2>
        
        <div class="contarea">
        
        	<div class="sections">
        	<img src="/themes/hostingycloud/images/site-icon15.png" alt="" />
            <h4>Web Designing Services</h4>
            <p>We offer web design services for your businesses and personals.</p>
            </div><!-- end section -->
            
            <div class="clearfix divider_line4"></div>
            
            <div class="sections">
        	<img src="/themes/hostingycloud/images/site-icon16.png" alt="" />
            <h4>Join Affiliate Program!</h4>
            <p>Affiliates get higher commission Become an affiliate today.</p>
            </div><!-- end section -->
            
        </div>
    
    </div><!-- end whats new -->
    
</div><!-- end all sections -->

<div class="clearfix mar_top3"></div>

<div class="hosting_plans">

<div class="container">

	<div class="title_text"><img src="/themes/hostingycloud/images/text-hostinclu.png" alt="" /></div>
    
    	<div class="hostplan">
        	<div class="title"><b>$ 2.99 <br /><i>per month</i></b> <strong>Standard hosting</strong></div>
            <ul>
            <li>500 GB Disk Space</li>
            <li>100 Databases List</li>
            <li>Free Domain Registration</li>
            <li>1 Hosting Space</li>
            <li>FREE Ad Coupons</li>
            <li>Account Control Panel</li>
            <li>FREE 24/7 Support</li>
            <li class="noarrow"><a href="#" class="black_button">sign up now!</a></li>
            </ul>
            <div class="shadow"></div>
        </div><!-- end host plan -->
        
        <div class="hostplan">
        	<div class="title"><b>$ 4.99 <br /><i>per month</i></b> <strong>Professional hosting</strong></div>
            <ul>
            <li>Unlimited Disk Space</li>
            <li>100 Databases List</li>
            <li>Free Domain Registration</li>
            <li>1 Hosting Space</li>
            <li>FREE Ad Coupons</li>
            <li>Account Control Panel</li>
            <li>FREE 24/7 Support</li>
            <li class="noarrow"><a href="#" class="black_button">sign up now!</a></li>
            </ul>
            <div class="shadow"></div>
        </div><!-- end host plan -->
        
        <div class="hostplan">
        	<div class="title"><b>$ 45 <br /><i>per month</i></b> <strong>Advanced hosting</strong></div>
            <ul>
            <li>Unlimited Disk Space</li>
            <li>100 Databases List</li>
            <li>Free Domain Registration</li>
            <li>1 Hosting Space</li>
            <li>FREE Ad Coupons</li>
            <li>Account Control Panel</li>
            <li>FREE 24/7 Support</li>
            <li class="noarrow"><a href="#" class="black_button">sign up now!</a></li>
            </ul>
            <div class="shadow"></div>
        </div><!-- end host plan -->
        
        <div class="hostplan last">
        	<div class="title"><b>$ 99 <br /><i>per month</i></b> <strong>Unlimited hosting</strong></div>
            <ul>
            <li>Unlimited Disk Space</li>
            <li>100 Databases List</li>
            <li>Free Domain Registration</li>
            <li>1 Hosting Space</li>
            <li>FREE Ad Coupons</li>
            <li>Account Control Panel</li>
            <li>FREE 24/7 Support</li>
            <li class="noarrow"><a href="#" class="black_button">sign up now!</a></li>
            </ul>
            <div class="shadow"></div>
        </div><!-- end host plan -->
    
    </div>

</div><!-- end all hosting plans -->

<div class="clearfix mar_top3"></div>

<div class="container">
	
    <div class="home_aboutarea">
    	<div class="left"><img src="/themes/hostingycloud/images/site-img19.png" alt="" /></div>
    	<div class="right">
        <h2>We’ll just take care of it for you!</h2>
        <p>We will provide you with a hassle free web hosting service where we we take care. The majority have suffered alterations in some form injected humour, or randomiseds words which dont look the even slightly believable. If you are going to use a passagea lorem Ipsum you need to be sure there anythin embaras middle desktop publishing software like aldus pageMaker including versions.</p>
        </div>
    </div><!-- end section -->
    
    
    <div class="accrodation">
    	
       <!-- section 1 -->
        <span class="acc-trigger active"><a href="#">What is web hosting?</a></span>
        <div class="acc-container">
        <div class="content">
        There are many variations of passages of Lorem Ipsum available but the
        </div>
        </div>
      
        <!-- section 3 -->
        <span class="acc-trigger"><a href="#">What is a domain name?</a></span>
        <div class="acc-container">
        <div class="content">
        There are many variations of passages of Lorem Ipsum available but the
        </div>
        </div>
               
        <!-- section 5 -->
        <span class="acc-trigger"><a href="#">How do I create my web site?</a></span>
        <div class="acc-container">
        <div class="content">
        There are many variations of passages of Lorem Ipsum available but the
        </div>
        </div>
        
    </div>
      
    
</div>

<div class="clearfix mar_top13"></div>

<div class="features_section_two">
	
    <div class="container">
    
        <div class="sections">
        
        	<h2>What’s Included ?</h2>
            
            <ul class="hosting_includes_list">
            
            	<li>
                <img src="/themes/hostingycloud/images/host-includes-icon1.png" alt="" />
                <h4>Free Website Builde</h4>
                </li>
                <li>
                <img src="/themes/hostingycloud/images/host-includes-icon2.png" alt="" />
                <h4>Free Domain Registration</h4>
                </li>
                <li>
                <img src="/themes/hostingycloud/images/host-includes-icon3.png" alt="" />
                <h4>Free Instant Setup!</h4>
                </li>
                <li>
                <img src="/themes/hostingycloud/images/host-includes-icon4.png" alt="" />
                <h4>e-Commerce Shop Carts</h4>
                </li>
                <li>
                <img src="/themes/hostingycloud/images/host-includes-icon5.png" alt="" />
                <h4>Free Email Accounts</h4>
                </li>
                <li>
                <img src="/themes/hostingycloud/images/host-includes-icon6.png" alt="" />
                <h4>cPanel &amp; Plesk Control Panel</h4>
                </li>
                
            </ul>
        
        </div><!-- end section-->
        
         <div class="sections">
        
            <h2>Creating a New Website?</h2>
            <img src="/themes/hostingycloud/images/site-img18.png" alt="" class="image_left8 mar_top13" />
            
        	<ul class="creating_newwebstie_list"> 
            	<li>Get Building Started in 3 Easy Steps</li>
                <li>Login to our Hosting Site Builder</li>
                <li>Lorem Ipsum is Simply Dummy text</li>
                
            </ul>
            
        </div><!-- end section-->
        
         <div class="sections last">
        	
            <div class="ad_one">
            	<div class="carve"></div>
            	<h2>Get up to</h2>
				<h1>25 % discount</h1>
				<h2>On all hosting orders</h2>
                <a href="#" class="but">sign up now!</a>
            </div><!-- end ad-->
            
            <div class="clearfix mar_top2"></div>
            
            <div class="ad_two">
            	<div class="carve"></div>
            	<h2>Just $9.99<i>/year*</i></h2>
				<h1>save big<i>/ on domains</i></h1>
				<h5>&nbsp;&nbsp;<i>.com</i>   <i>.net</i>    just 7.99 only</h5>
            </div><!-- end ad-->
        
        </div><!-- end section-->
        
    </div>

</div>

<div class="clearfix mar_top3"></div>

<div class="bottom_sections">

	<div class="container">
    	
        <div class="whyus">
        
        	<h2>Why Choose Us?</h2>
            
            <div class="whyus_box">
        		
                <ul class="whyus_list">
                	<li><img src="/themes/hostingycloud/images/site-icon20.png" alt="" /><h4>Domain Registration</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon21.png" alt="" /><h4>Web Hosting Services</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon22.png" alt="" /><h4>Reseller Web Hosting</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon23.png" alt="" /><h4>Virtual Servers</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon24.png" alt="" /><h4>Dedicated Hosting</h4></li>
                </ul>
                
                <ul class="whyus_list last">
                	<li><img src="/themes/hostingycloud/images/site-icon25.png" alt="" /><h4>Cloud Host Servers</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon26.png" alt="" /><h4>Apps Installs Easy</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon27.png" alt="" /><h4>Money Back Guarantee</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon28.png" alt="" /><h4>Secure Your Web site</h4></li>
                    <li><img src="/themes/hostingycloud/images/site-icon29.png" alt="" /><h4>Quality 24/7 Support</h4></li>
                </ul>
                
            </div>
        </div><!-- end why choose us-->
        
        
	<div class="people_says_main">
    
	<h2>What People Say’s</h2>
        	
	<div class="people_says">
            
        	<ul id="mycarousel" class="jcarousel-skin-tango">
            
                <li>
                    <img src="/themes/hostingycloud/images/quotes1.png" alt="" class="image_left7" />
                    <p>There are many variations of passages of Ipsum available but the  randomise words which don't look even slightly believable. there isn't anything hidden when looking desktop you need to be sure there isn't anything publishing packages in the middle of generators.</p>
					<img src="/themes/hostingycloud/images/quotes2.png" alt="" class="image_left11" />
                    <div class="who_pic">
                    <div class="name"><strong>- Mark Richardson</strong>
   					<i>custmer</i></div>
                    <div class="picture"><img src="/themes/hostingycloud/images/people1.png" alt="" /></div>
                    
                    </div>
                </li>
                
                <li>
                    <img src="/themes/hostingycloud/images/quotes1.png" alt="" class="image_left7" />
                    <p>Where are many variations of passages of Ipsum available but the  randomise words which don't look even slightly believable. there isn't anything hidden when looking desktop you need to be sure there isn't anything publishing packages in the middle of generators.</p>
					<img src="/themes/hostingycloud/images/quotes2.png" alt="" class="image_left11" />
                    <div class="who_pic">
                    <div class="name"><strong>- Madison Ava</strong>
   					<i>custmer</i></div>
                    <div class="picture"><img src="/themes/hostingycloud/images/people2.png" alt="" /></div>
                    
                    </div>
                </li>
                
                <li>
                    <img src="/themes/hostingycloud/images/quotes1.png" alt="" class="image_left7" />
                    <p>Phere are many variations of passages of Ipsum available but the  randomise words which don't look even slightly believable. there isn't anything hidden when looking desktop you need to be sure there isn't anything publishing packages in the middle of generators.</p>
					<img src="/themes/hostingycloud/images/quotes2.png" alt="" class="image_left11" />
                    <div class="who_pic">
                    <div class="name"><strong>- Jacob Alexander</strong>
   					<i>custmer</i></div>
                    <div class="picture"><img src="/themes/hostingycloud/images/people3.png" alt="" /></div>
                    
                    </div>
                </li>
   
          </ul>
        
    </div>
            
	</div>
        
    
	</div>

</div>




<div class="container_full">

	<div class="twitter_feed">
    
        <div class="container">
        
            <img src="/themes/hostingycloud/images/twitter-bird.png" alt="" class="image_left1" >
            
            <div class="tweets"><strong><a href="https://twitter.com/gsrthemes9" target="_blank">gsrthemes9:</a></strong> Kinvexy - Responsive HTML5 / CSS3, Simple, Clean and Professional theme Coming soon... A Multipurpose Template. <br />
                <ul>
                <li><a href="#">9 days ago</a></li>
                <li><a href="#">reply</a></li>
                <li><a href="#">retweet</a></li>
                <li><a href="#">favorite</a></li>
                </ul>
			</div>
        
        </div>
    
	</div>

</div>

