<!doctype html>
<!--[if IE 7 ]>    <html lang="en-gb" class="isie ie7 oldie no-js"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-gb" class="isie ie8 oldie no-js"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en-gb" class="isie ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en-gb" class="no-js"> <!--<![endif]-->

<head>

            <?php echo $this->headTitle("Smeagol CMS"); ?>
    	
	
	<meta charset="utf-8">
	<meta name="keywords" content="" />
	<meta name="description" content="" />
            <?php if ($is_login) { ?>
                <?php echo $this->headLink()->appendStylesheet($this->basePath() . '/admin/css/admin-style.css'); ?>
            <?php } ?>
            <?php if ($is_front) { ?>
            <?php } else { ?>
                <?php echo $this->headScript()->prependFile($this->basePath() . '/jquery-1.11.1.min.js'); ?>
            <?php } ?>

            <!-- this styles only adds some repairs on idevices  -->
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
                <!-- Google fonts - witch you want to use - (rest you can just remove) -->
                <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>

                    <!--[if lt IE 9]>
                                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
                        <![endif]-->

                    <!-- ######### CSS STYLES ######### -->

                    <link rel="stylesheet" href="/themes/hostingycloud/css/reset.css" type="text/css" />
                    <link rel="stylesheet" href="/themes/hostingycloud/css/style.css" type="text/css" />

                    <!-- responsive devices styles -->
                    <link rel="stylesheet" media="screen" href="/themes/hostingycloud/css/responsive-leyouts.css" type="text/css" />


                    <!-- just remove the below comments witch color skin you want to use -->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/orange.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/lightgreen.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/blue.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/green.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/red.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/cyan.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/purple.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/yellow.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/colors/brown.css" />-->



                    <!-- just remove the below comments witch bg patterns you want to use -->

                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-default.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-one.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-two.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-three.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-four.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-five.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-six.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-seven.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-eight.css" />-->
                    <!--<link rel="stylesheet" href="/themes/hostingycloud/css/bg-patterns/pattern-nine.css" />-->

                    <!-- style switcher -->
                    <link rel = "stylesheet" media = "screen" href = "/themes/hostingycloud/js/style-switcher/color-switcher.css" />

                    <!-- jquery jcarousel -->
                    <link rel="stylesheet" type="text/css" href="/themes/hostingycloud/js/jcarousel/skin.css" />

                    <!-- REVOLUTION SLIDER -->
                    <link rel="stylesheet" type="text/css" href="/themes/hostingycloud/js/revolutionslider/css/fullwidth.css" media="screen" />
                    <link rel="stylesheet" type="text/css" href="/themes/hostingycloud/js/revolutionslider/rs-plugin/css/settings.css" media="screen" />

                    <!-- faqs -->
                    <link rel="stylesheet" href="/themes/hostingycloud/js/accordion/accordion.css" type="text/css" media="all">

        </head>
        <body>
            <!--
                <?php if ($is_login) { ?>
                <div id="menu_div">
                    <div id="navigation-admin">   
                        <div id="menu">
                            <?php echo $this->navigation("admin_menus")->setAcl($this->acl)->setRole($this->role); ?>
                        </div>
                    </div>
                </div>
                <?php } ?>      
                           <div id="login">
                                <?php if (!$is_login) { ?>                     
                                    <a href="<?php echo $this->basePath(); ?>/login" title="Login"><span>Login</span></a>
                                <?php } else { ?>                
                                    <a href="<?php echo $this->basePath(); ?>/logout" title="Logout"><span>Logout</span></a>
                                <?php } ?>
                            </div>		
                            <br/><br/>
                            <div id="navigation">   
                                <?php echo $this->navigation("primary_menus")->setAcl($this->acl)->setRole($this->role); ?>
                            </div>
            -->
                            <?php echo $this->content; ?>

            </body>
</html>