<?php echo $this->headTitle($node->title . " "); ?>
<div class="page_title">

    <div class="container">
        <div class="leaft_title"><h1><?php echo $node->title; ?></h1></div>
        <!--
        <div class="reght_pagenation"><a href="index.html">Home</a> <i>/</i> <a href="#">Web Hosting</a> <i>/</i> Professional Hosting</div>
        -->
    </div>

</div><!-- end page title -->

<div class="clearfix"></div>

<div class="container">
    <div class="content_fullwidth">
        <div class="hosting_page_plan_main">
            <?php echo $node->content; ?>
        </div>
    </div>
</div>
<div class="clearfix mar_top3"></div>